#index:
#    path: /
#    controller: App\Controller\DefaultController::index


auth:
  path: auth/register
  controller: App\Controller\AuthController::register

login:
  path: auth/login
  controller: App\Controller\AuthController::login
api:
  path: api/test
  controller: App\Controller\ApiController::index

createorder:
  path: api/createorder
  controller: App\Controller\ApiController::createorder

updateOrder:
  path: api/updateorder
  controller: App\Controller\ApiController::updateorder

getorders:
  path: api/getorders
  controller: App\Controller\ApiController::getorders

getorder:
  path: api/{ordercode}/getorder
  controller: App\Controller\ApiController::getorder